### ISSUE TITLE
Hog crashes pycbir

### ISSUE THREAD

**Issue by dani-lbnl** [xdatacnn/imagesearch#4]
pyCBIR started!
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    1.6s
[Parallel(n_jobs=-1)]: Done  43 out of  58 | elapsed:    1.7s remaining:    0.6s
[Parallel(n_jobs=-1)]: Done  55 out of  58 | elapsed:    1.7s remaining:    0.1s
[Parallel(n_jobs=-1)]: Done  58 out of  58 | elapsed:    1.7s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  55 out of  58 | elapsed:    0.0s remaining:    0.0s
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/dani/anaconda3/envs/pycbirEnv/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/Users/dani/anaconda3/envs/pycbirEnv/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/dani/anaconda3/envs/pycbirEnv/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/Users/dani/anaconda3/envs/pycbirEnv/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/Users/dani/anaconda3/envs/pycbirEnv/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "../src/signatures/hog_rom.py", line 26, in HOG
    angles2=angles[n*step_y+1:(n+2)*step_y,m*step_x+1:(m+2)*step_x]
TypeError: slice indices must be integers or None or have an __index__ method
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dani/Dropbox/prog/python/pyCBIR_code/imagesearch/src/interface/gui.py", line 692, in returnInformation
    _,_,file = run.run_command_line(fname_database,labels_database,fname_retrieval,labels_retrieval,self.path_cnn_pre_trained, self.path_save_cnn, self.lineEdit_2.text(),self.feature_extraction_method,self.similarity_metric,retrieval_number,self.list_of_parameters,preprocessing_method,searching_method, isEvaluation = False)
  File "/Users/dani/Dropbox/prog/python/pyCBIR_code/imagesearch/src/run.py", line 421, in run_command_line
    fname_database,feature_vectors_database,labels_database = fe.descriptor_all_database(fname_database,labels_database,feature_extraction_method,list_of_parameters,preprocessing_method)
  File "../src/signatures/feature_extraction.py", line 125, in descriptor_all_database
    aux = descriptor(collection, collection_filenames, labels,feature_extraction_method,list_of_parameters)
  File "../src/signatures/feature_extraction.py", line 90, in descriptor
    features = parallel.apply_parallel(collection, collection_filenames, labels, hog_rom.HOG, {"cells": int(list_of_parameters[0]), "blocks": int(list_of_parameters[1])})
  File "../src/util/parallel.py", line 38, in apply_parallel
    res = joblib.Parallel(n_jobs=-1, verbose=5)(joblib.delayed(func)(image_collection[nr], collection_filenames[nr], labels[nr], **kwargs) for nr in range(len(image_collection)))
  File "/Users/dani/anaconda3/envs/pycbirEnv/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/Users/dani/anaconda3/envs/pycbirEnv/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/dani/anaconda3/envs/pycbirEnv/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/dani/anaconda3/envs/pycbirEnv/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/dani/anaconda3/envs/pycbirEnv/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by dani-lbnl** [comment]
Also crashes for cell dataset!!!
