### ISSUE TITLE
RT crashes pycbir

### ISSUE THREAD

**Issue by dani-lbnl** [xdatacnn/imagesearch#5]
pyCBIR started!
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   4 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   4 out of   4 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   4 out of   4 | elapsed:    0.0s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   4 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   4 out of   4 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   4 out of   4 | elapsed:    0.0s finished
Features Extracted!
Traceback (most recent call last):
  File "/Users/dani/Dropbox/prog/python/pyCBIR_code/imagesearch/src/interface/gui.py", line 692, in returnInformation
    _,_,file = run.run_command_line(fname_database,labels_database,fname_retrieval,labels_retrieval,self.path_cnn_pre_trained, self.path_save_cnn, self.lineEdit_2.text(),self.feature_extraction_method,self.similarity_metric,retrieval_number,self.list_of_parameters,preprocessing_method,searching_method, isEvaluation = False)
  File "/Users/dani/Dropbox/prog/python/pyCBIR_code/imagesearch/src/run.py", line 440, in run_command_line
    result = searching.searching(feature_vectors_database,feature_vectors_retrieval, labels_database, fname_database,similarity_metric,retrieval_number,list_of_parameters,feature_extraction_method,path_output,searching_method)
  File "../src/similarity/searching.py", line 67, in searching
    path_output,searching_method)
  File "../src/similarity/searching.py", line 157, in searching_RTree
    p = index.Property()
NameError: name 'index' is not defined

**Comment by dani-lbnl** [comment]
solved just before release at ALS user meeting
